
services:
  house-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api.py
      - SQLALCHEMY_DATABASE_URI=postgresql://amina:23012006@db:5432/housing_db
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: amina
      POSTGRES_PASSWORD: 23012006
      POSTGRES_DB: housing_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
