"""Create houses table

Revision ID: 6f0c3bb52505
Revises: 
Create Date: 2025-03-02 23:40:31.188238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0c3bb52505'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('housing_median_age', sa.Integer(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('total_bedrooms', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('median_income', sa.Float(), nullable=False),
    sa.Column('median_house_value', sa.Float(), nullable=False),
    sa.Column('ocean_proximity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    # ### end Alembic commands ###
